### ISSUE TITLE
 [Feature request] openaudio integration

### ISSUE THREAD

**Issue by RustoMCSpit** [igorski/fogpad#6]
https://github.com/open-audio-stack/open-audio-stack-registry

i can add this and all of your plugins if you put them into github releases

openaudio is the foss plugin manager that is used by owlplug, studiorack, etc...

@igorski

**Comment by igorski** [comment]
Hi there, just saw your addition of the Regrader plugin to the registry. Apologies for not replying to the issue you recreated there a considerable while back.

The idea sounds interesting, I need to invest some time in understanding how it works and how the binaries can best be distributed for this purpose (as the website URLs will expire and not point to specific versioned releases in the future). Could we point towards binaries attached to the Github releases (the Regrader repository now includes these) ?

**Comment by RustoMCSpit** [comment]
> Could we point towards binaries attached to the Github releases (the Regrader repository now includes these) ?

@igorski yes! please just put them into .zip files. it's very easy to contribute plugins, just fill in the metadata on a ,yaml file, add a picture, and add a sound of it playing something. also, you dont need a linux distribution but if youd be willing id love to add these to my list https://github.com/RustoMCSpit/awesome-linux-clap-list

e.g.

https://github.com/open-audio-stack/open-audio-stack-registry/commit/53121203c9314babff4616f941400ac859738640#diff-bfe7b2fe191c65ec5c97c0f15b3ddf8dbd392799f885c522dc213ce94d69162c

```
---
audio: https://open-audio-stack.github.io/open-audio-stack-registry/plugins/igorski/regrader/regrader.flac
author: Igor Zinken
changes: |
  - Built using Steinberg SDK version 3.7.10.14
date: '2024-03-16T07:00:00.000Z'
description: Delay effect in which the repeats degrade in various ways. Delay repeats can be synced to the host tempo and time signature and be fully automated.
files:
  - architectures:
      - x64
    contains:
      - component
      - vst
      - vst3
    format: zip
    sha256: cd35563df0b5fef0d5afcc7ccddd69eeb2fb40b1c85a8dc99347d3b56a2a67db
    systems:
      - type: mac
    size: 10002246
    type: archive
    url: https://www.igorski.nl/download/retrieve/f906e0f712838e188155bfdf1bbc4510e204fdd54e9c85fe661da357b7ad91d5/2
  - architectures:
      - x64
    contains:
      - dll
      - vst3
    format: zip
    sha256: 3141f43f3e6445f154395c1da1221c2931b1dfd5140f0207b8a4b8052b8fb574
    systems:
      - type: win
    size: 2858396
    type: archive
    url: https://www.igorski.nl/download/retrieve/f906e0f712838e188155bfdf1bbc4510e204fdd54e9c85fe661da357b7ad91d5
image: https://open-audio-stack.github.io/open-audio-stack-registry/plugins/igorski/regrader/regrader.jpg
license: mit
name: Regrader
tags:
  - Effect
  - Delay
  - Sync
type: effect
url: https://github.com/igorski/regrader
```
